### ISSUE TITLE
it is not compatible with NodeBB 1.19.X

### ISSUE THREAD

**Issue by AliCihan** [exo-do/nodebb-plugin-ignore-users#33]
Would it be possible to fix the incompatibility ? Thanks.

**Comment by AliCihan** [comment]
We get this error log in 1.19.1: 

```
2022-01-30T19:27:57.066Z [4567/3613114] - [33mwarn[39m:    [plugins/nodebb-plugin-ignore-users] The plugin.json field "library" is deprecated. Please use the package.json field "main" instead.
2022-01-30T19:27:57.067Z [4567/3613114] - [33mwarn[39m: [plugins] Unable to load library for: nodebb-plugin-ignore-users
2022-01-30T19:27:57.069Z [4567/3613114] - [31merror[39m: Error: Cannot find module './socket.io/modules'
Require stack:
- /home/fsuzer/nodebb/src/plugins/index.js
- /home/fsuzer/nodebb/src/meta/configs.js
- /home/fsuzer/nodebb/src/meta/index.js
- /home/fsuzer/nodebb/src/start.js
- /home/fsuzer/nodebb/require-main.js
- /home/fsuzer/nodebb/app.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at /home/fsuzer/nodebb/node_modules/nodebb-plugin-ignore-users/library.js:6:32
    at Object.<anonymous> (/home/fsuzer/nodebb/node_modules/nodebb-plugin-ignore-users/library.js:459:2)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```
